PROGRAM main

IMPLICIT NONE
INTEGER, ALLOCATABLE :: a(:)
INTEGER :: x
CALL sub1(a(1),a(1))
CALL sub1(x,x)

CONTAINS
SUBROUTINE sub1(x1,x2)
INTEGER, INTENT(IN)  :: x1
INTEGER, INTENT(OUT) :: x2
x2 = 1
END SUBROUTINE sub1
END PROGRAM
